spring:
  security:
    filter:
      order: 10
    user:
      password: Test1234
      name: user
  datasource:
    url: jdbc:mysql://eu-cdbr-west-01.cleardb.com/heroku_45ffe98c65636d2?reconnect=true
    username: b76ab84075684e
    password: f6ebd6c9
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
  messages:
    basename: messages/messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: learning.app.botmail@gmail.com
    password: haslo1410
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082
