spring:
  security:
    filter:
      order: 10
    user:
      password: Test1234
      name: user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learning_application_DB?serverTimezone=CET
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: verify
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
  messages:
    basename: messages/messages
server:
  port: 8081
