spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learning_application_DB?serverTimezone=CET
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  messages:
    basename: messages/messages
