spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learning_application_DB?serverTimezone=CET
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
  messages:
    basename: messages/messages
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
server:
  port: 8081
  servlet:
    context-path: /resource-server
