spring:
  security:
    filter:
      order: 10
    user:
      password: Test1234
      name: user
  datasource:
    url: jdbc:mysql://remotemysql.com/sF26fF66k5?serverTimezone=CET&createDatabaseIfNotExist=true
    username: sF26fF66k5
    password: nrDLvi1vXZ
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
  messages:
    basename: messages/messages
